# Numpy
NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as [masked arrays](https://numpy.org/doc/stable/reference/maskedarray.html) and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the [ndarray](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) object. This encapsulates n-dimensional arrays of homogeneous data types, with many operations being performed in compiled code for performance. There are several important differences between NumPy arrays and the standard Python sequences:

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory. The exception: one can have arrays of (Python, including NumPy) objects, thereby allowing for arrays of different sized elements.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays. In other words, in order to efficiently use much (perhaps even most) of today’s scientific/mathematical Python-based software, just knowing how to use Python’s built-in sequence types is insufficient - one also needs to know how to use NumPy arrays.

## Starter
- Install via CMD: `pip install numpy`
- Import numpy: `import numpy as np`
- Check version: `np.__version__`


## URLs
- [Numpy-Official-Docs](https://numpy.org/)
- [Array creation](https://numpy.org/doc/stable/user/basics.creation.html)
- [Data types](https://numpy.org/doc/stable/user/basics.types.html)
- [`numpy.linspace`](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html)
- [`numpy.arange`](https://numpy.org/doc/stable/reference/generated/numpy.arange.html)
- [`numpy.eye`](https://numpy.org/doc/stable/reference/generated/numpy.eye.html#numpy.eye)
- [`numpy.diag`](https://numpy.org/doc/stable/reference/generated/numpy.diag.html#numpy.diag)
- [`numpy.vander`](https://numpy.org/doc/stable/reference/generated/numpy.vander.html#numpy.vander)
- [`numpy.ones`](https://numpy.org/doc/stable/reference/generated/numpy.ones.html#numpy.ones)
- [`numpy.zeros`](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html#numpy.zeros)
- [`random`](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.random.html#numpy.random.Generator.random)
- [`default_rng`](https://numpy.org/doc/stable/reference/random/generator.html)
- [`numpy.random`](https://numpy.org/doc/stable/reference/random/index.html#module-numpy.random)
- [`numpy.indices`](https://numpy.org/doc/stable/reference/generated/numpy.indices.html#numpy.indices)
- [`numpy.copy`](https://numpy.org/doc/stable/reference/generated/numpy.copy.html#numpy.copy)
- [Copies and Views](https://numpy.org/doc/stable/user/quickstart.html#quickstart-copies-and-views)

In [1]:
import numpy as np

In [2]:
np.__version__

'1.24.3'

## [Array creation](https://numpy.org/doc/stable/user/basics.creation.html)

There are 6 general mechanisms for creating arrays:
1. Conversion from other Python structures (i.e. lists and tuples)
1. Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)
1. Replicating, joining, or mutating existing arrays
1. Reading arrays from disk, either from standard or custom formats
1. Creating arrays from raw bytes through the use of strings or buffers
1. Use of special library functions (e.g., random)

### 1. Converting Python sequences to NumPy Arrays
NumPy arrays can be defined using Python sequences such as lists and tuples. Lists and tuples are defined using [...] and (...), respectively. Lists and tuples can define ndarray creation:
- a list of numbers will create a 1D array,
- a list of lists will create a 2D array,
- further nested lists will create higher-dimensional arrays. In general, any array object is called an ndarray in NumPy.

In [3]:
a1D = np.array([1, 2, 3, 4])
a2D = np.array([[1, 2], [3, 4]])
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [4]:
a1D

array([1, 2, 3, 4])

In [5]:
a2D

array([[1, 2],
       [3, 4]])

In [6]:
a3D

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

[Data types](https://numpy.org/doc/stable/user/basics.types.html)

Sebelumnya telah disinggung bahwa setiap elemen pada `numpy.array` diharuskan agar memiliki tipe data yang sama. Dengan demikian, mengenal dan memahami prilaku setiap tipe data, setidaknya tipe data yang umum, menjadi esensial.

| Numpy type   | C type        | Description                                                                                      |
|--------------|---------------|--------------------------------------------------------------------------------------------------|
| numpy.bool_  | bool          | Boolean (True or False) stored as a byte                                                         |
| numpy.int_   | long          | Platform-defined                                                                                 |
| numpy.uint   | unsigned long | Platform-defined                                                                                 |
| numpy.single | float         | Platform-defined single precision float: typically sign bit, 8 bits exponent, 23 bits mantissa   |
| numpy.double | double        | Platform-defined double precision float: typically sign bit, 11 bits exponent, 52 bits mantissa. |

In [7]:
a = 1.0
print(type(a))
a = np.float32(a)
print(type(a))

<class 'float'>
<class 'numpy.float32'>


When you use `numpy.array` to define a new array, you should consider the `dtype` of the elements in the array, which can be specified explicitly. This feature gives you more control over the underlying data structures and how the elements are handled in C/C++ functions. If you are not careful with `dtype` assignments, you can get unwanted overflow, as such

In [8]:
a = np.array([127, 128, 129], dtype=np.int8)
a

C:\Users\Kamal\AppData\Local\Temp\ipykernel_16648\337030010.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 128 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  a = np.array([127, 128, 129], dtype=np.int8)
C:\Users\Kamal\AppData\Local\Temp\ipykernel_16648\337030010.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 129 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  a = np.array([127, 128, 129], dtype=np.int8)


array([ 127, -128, -127], dtype=int8)

An 8-bit signed integer represents integers from -128 to 127. Assigning the int8 array to integers outside of this range results in overflow.

Pandang `np.int8` sebagai barisan siklik integer dari -128 hingga 127. Untuk array dengan `dtype` berupa `np.int8`, nilai integer yang valid adalah merentang dari -128 hingga 127; jika di luar range tersebut, maka akan *overflow*, yaitu kembali ke awal barisan `np.int8`.

This feature can often be misunderstood. If you perform calculations with mismatching dtypes, you can get unwanted results, for example:

In [9]:
a = np.array([2, 3, 4], dtype=np.uint32)
b = np.array([5, 6, 7], dtype=np.uint32)
c_unsigned32 = a - b
print('unsigned c:', c_unsigned32, c_unsigned32.dtype)

unsigned c: [4294967293 4294967293 4294967293] uint32


In [10]:
c_signed32 = a - b.astype(np.int32)
print('signed c:', c_signed32, c_signed32.dtype)

signed c: [-3 -3 -3] int64


In [11]:
c_signed32 = a.astype(np.int32)  - b
print('signed c:', c_signed32, c_signed32.dtype)

signed c: [-3 -3 -3] int64


In [12]:
c_signed32 = a.astype(np.int32)  - b.astype(np.int32)
print('signed c:', c_signed32, c_signed32.dtype)

signed c: [-3 -3 -3] int32


Notice when you perform operations with two arrays of the same `dtype`: `uint32`, the resulting array is the same type. When 
you perform operations with different `dtype`, NumPy will assign a new type that satisfies all of the array elements involved in the computation, here `uint32` and `int32` can both be represented in as int64.

The default NumPy behavior is to create arrays in either 32 or 64-bit signed integers (platform dependent and matches C long size) or double precision floating point numbers. If you expect your integer arrays to be a specific type, then you need to specify the dtype while you create the array.

#### 2. Intrinsic NumPy array creation functions
NumPy has over 40 built-in functions for creating arrays as laid out in the Array creation routines. These functions can be split into roughly three categories, based on the dimension of the array they create:
1. 1D arrays
1. 2D arrays
1. ndarrays

*1D array creation functions*

The 1D array creation functions e.g. [`numpy.linspace`](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html) and [`numpy.arange`](https://numpy.org/doc/stable/reference/generated/numpy.arange.html) generally need at least two inputs, start and stop.

`numpy.arange` creates arrays with regularly incrementing values.

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(2, 10, dtype=float)
#np.arange(2, 10, dtype='float')
#np.arange(2, 10, dtype='float32')

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [15]:
np.arange(2, 3, 0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

Note: best practice for numpy.arange is to use integer start, end, and step values. There are some subtleties regarding dtype. In the second example, the dtype is defined. In the third example, the array is dtype=float to accommodate the step size of 0.1. Due to roundoff error, the stop value is sometimes included.

`numpy.linspace` will create arrays with a specified number of elements, and spaced equally between the specified beginning and end values. For example:

In [16]:
np.linspace(1., 4., 6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

The advantage of this creation function is that you guarantee the number of elements and the starting and end point. The previous `arange(start, stop, step)` will not include the value `stop`.

*2D array creation functions*

The 2D array creation functions e.g. [numpy.eye](https://numpy.org/doc/stable/reference/generated/numpy.eye.html#numpy.eye), [numpy.diag](https://numpy.org/doc/stable/reference/generated/numpy.diag.html#numpy.diag), and [numpy.vander](https://numpy.org/doc/stable/reference/generated/numpy.vander.html#numpy.vander) define properties of special matrices represented as 2D arrays.

`np.eye(n, m)` defines a 2D identity matrix. The elements where `i=j` (row index and column index are equal) are 1 and the rest are 0, as such:

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
np.eye(3, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

`numpy.diag` can define either a square 2D array with given values along the diagonal or if given a 2D array returns a 1D array that is only the diagonal elements.

`numpy.diag` mempertimbangkan apakah input berupa array 1D atau array 2D.

The two array creation functions can be helpful while doing linear algebra, as such:

In [19]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

Diagonal in question. The default is 0. Use `k>0` for diagonals above the main diagonal, and `k<0` for diagonals below the main diagonal.

In [20]:
np.diag([1, 2, 3], 0)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [21]:
np.diag([1, 2, 3], 1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [22]:
np.diag([1, 2, 3], k=-2)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0]])

In [23]:
a = np.array([[1, 2], [3, 4]])
np.diag(a)

array([1, 4])

`vander(x, n)` defines a Vandermonde matrix as a 2D NumPy array. Each column of the Vandermonde matrix is a decreasing power of the input 1D array or list or tuple, `x` where the highest polynomial order is `n-1`. This array creation routine is helpful in generating linear least squares models, as such:

In [24]:
np.vander(np.linspace(0, 2, 5), 2)

array([[0. , 1. ],
       [0.5, 1. ],
       [1. , 1. ],
       [1.5, 1. ],
       [2. , 1. ]])

In [25]:
np.vander([1, 2, 3, 4], 2)

array([[1, 1],
       [2, 1],
       [3, 1],
       [4, 1]])

In [26]:
np.vander((1, 2, 3, 4), 4)

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

### 2. General ndarray creation functions

The ndarray creation functions e.g. [`numpy.ones`](https://numpy.org/doc/stable/reference/generated/numpy.ones.html#numpy.ones), [`numpy.zeros`](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html#numpy.zeros), and [`random`](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.random.html#numpy.random.Generator.random) define arrays based upon the desired shape. The ndarray creation functions can create arrays with any dimension by specifying how many dimensions and length along that dimension in a tuple or list.

`numpy.zeros` will create an array filled with 0 values with the specified shape. The default dtype is `float64`:

In [27]:
np.zeros(3)

array([0., 0., 0.])

In [28]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [30]:
np.zeros((2,3,4,5))

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

`numpy.ones` will create an array filled with 1 values. It is identical to zeros in all other respects as such:

In [31]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

The [`random`](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.random.html#numpy.random.Generator.random) method of the result of [`default_rng`](https://numpy.org/doc/stable/reference/random/generator.html) will create an array filled with random values between 0 and 1. It is included with the [`numpy.random`](https://numpy.org/doc/stable/reference/random/index.html#module-numpy.random) library. Below, two arrays are created with shapes (2,3) and (2,3,2), respectively. The seed is set to 42 so you can reproduce these pseudorandom numbers:

In [32]:
from numpy.random import default_rng
default_rng(42).random((2,3))

array([[0.77395605, 0.43887844, 0.85859792],
       [0.69736803, 0.09417735, 0.97562235]])

In [33]:
default_rng(42).random((2,3,2))

array([[[0.77395605, 0.43887844],
        [0.85859792, 0.69736803],
        [0.09417735, 0.97562235]],

       [[0.7611397 , 0.78606431],
        [0.12811363, 0.45038594],
        [0.37079802, 0.92676499]]])

In [34]:
type(default_rng())

numpy.random._generator.Generator

`default_rng()` adalah objek generator; jika di-print pun belum ada yang bisa ditampilkan karena masih abstrak. Jika argument `seed` tidak diberikan, maka setiap running akan memberikan hasil yang berbeda-beda.

[`numpy.indices`](https://numpy.org/doc/stable/reference/generated/numpy.indices.html#numpy.indices) will create a set of arrays (stacked as a one-higher dimensioned array), one per dimension with each representing variation in that dimension:

In [35]:
np.indices((3,3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

This is particularly useful for evaluating functions of multiple dimensions on a regular grid.

Ingat bahwa `numpy.indices` merupakan `numpy.ndarray`; `numpy.indices` merupakan himpunan dari elemen dengan setiap elemen bisa merupakan himpunan ataupun non-himpunan. Misalkan \$ G \$ merupakan `numpy.ndarray` berdimensi-\$n\$ dengan himpunan $$N = \lbrace \lbrace x_1, x_2, ..., {x}_{k_{1}} \rbrace, \lbrace x_1, x_2, ..., {x}_{k_{2}} \rbrace, ..., \lbrace x_1, x_2, ..., {x}_{k_{n}} \rbrace \rbrace $$
untuk
\$ x_{k_1}, x_{k_2}, ..., x_{k_{n}} \$ adalah anggota bilangan asli. Maka *regular grid* dari `numpy.indices` yang terbentuk - dengan sehimpunan grid points \$P\$ (discrete points or nodes in a grid or lattice) - adalah
$$ P = \lbrace \rbrace $$

Misalkan fungsi \$f_G(z_1,z_2,...,z_n) \$ memetakan tupel \$ (z_1,z_2,...,z_n) \$ kepada elemen `numpy.ndarray` \$ G[z_1][z_2]...[z_n] \$.

???

\$p = ( f_G(1, k_{2_{i_1}}, k_{3_{i_2}},...,k_{n_{i_{n-1}}}) , f_G(2, k_{2_{i_1}}, k_{3_{i_2}},...,k_{n_{i_{n-1}}}) , ... , f_G(3, k_{2_{i_1}}, k_{3_{i_2}},...,k_{n_{i_{n-1}}}) ) \$

???

Perhatikan bahwa setiap unit grid point \$p = (x'_0, x'_1,...,x'\_{n-1}) \in P \$ merupakan titik dengan tupel dari \$n\$ buah elemen.

-______- mau syarah sendiri, belum kelar buat bahasa math nya

### 3. Replicating, joining, or mutating existing arrays
Once you have created arrays, you can replicate, join, or mutate those existing arrays to create new arrays. When you assign an array or its elements to a new variable, you have to explicitly [`numpy.copy`](https://numpy.org/doc/stable/reference/generated/numpy.copy.html#numpy.copy) the array, otherwise the variable is a view into the original array.

Ini adalah fundamental yang sangat penting dalam menggunakan array dari numpy, terutama agar tidak terjadi kesalahan ketika diperlukan proses membuat array baru dari yang telah ada. Jika suatu variable baru akan dibuat dari array yang sudah ada tanpa melakukan `numpy.copy`, maka variable baru tersebut masih akan tetap berasosiasi dengan array awal; apabila ada suatu proses yang mengubah array baru, maka array yang lama akan berubah. Perhatikan bahwa method `numpy.copy` merupakan method yang melakukan returns value sehingga hasilnya bisa ditampung di suatu variable.

Consider the following example:

In [36]:
a = np.array([1, 2, 3, 4, 5, 6])
print('a =', a)
b = a[:2]
print('b =', b)
b += 1
print('a =', a, '; b =', b)

a = [1 2 3 4 5 6]
b = [1 2]
a = [2 3 3 4 5 6] ; b = [2 3]


Padahal yang diinginkan adalah array pada variable `b` berubah tanpa adanya perubahan pada variable `a`. Pada contoh ini dapat dikatakan bahwa fungsi viewing dalam array bermanfaat untuk memudahkan dalam mengubah elemen suatu array tanpa harus (selalu) mengakses (indexing, slicing, dll) atau mengevaluasi keseluruhan array tersebut.

In this example, you did not create a new array. You created a variable, `b` that viewed the first 2 elements of `a`. When you added 1 to `b` you would get the same result by adding 1 to `a[:2]`. If you want to create a new array, use the `numpy.copy` array creation routine as such:

In [37]:
a = np.array([1, 2, 3, 4])
print('a =', a)
b = a[:2].copy()
print('b =', b)
b += 1
print('a = ', a, 'b = ', b)

a = [1 2 3 4]
b = [1 2]
a =  [1 2 3 4] b =  [2 3]


For more information and examples look at [Copies and Views](https://numpy.org/doc/stable/user/quickstart.html#quickstart-copies-and-views). Tiga hal yang dibahas adalah:
- No Copy at All
- View or Shallow Copy
- Deep Copy

<center><strong>[BEGIN][ISOLATED_SECTION]</strong> Copies and Views</center>

#### *No Copy at All*

Simple assignments make no copy of objects or their data; no new object is created; two (variable) names for the same ndarray object.

In [38]:
a = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])
b = a # no new object is created
b is a # a and b are two names for the same ndarray object

True

Perlu diketahui bahwa dua buah object tidak dikatakan sama hanya karena memiliki elemen yang sama.

In [39]:
a_test = np.array([1,2,3])
b_test = np.array([1,2,3])
b_test is a_test

False

Python passes mutable objects as references, so function calls make no copy.

In [40]:
def f(x):
    print(id(x))

In [41]:
id(a)

2340242946544

In [42]:
f(a)

2340242946544


In [43]:
c_test = 1416 # integer; immutable

In [44]:
id(c_test)

2340240503376

In [45]:
f(c_test)

2340240503376


Kurang paham maksudnya; jadi kasus seperti apa sehingga pemanggilan function membuat copy?

#### *View or Shallow Copy*

Different array objects can share the same data. The view method creates a new array object that looks at the same data.

In [46]:
c = a.view()
c is a

False

Instead, `c` is a view of the data owned by `a`

In [47]:
c.base is a

True

Shape dari `a` tidak berubah sekalipun shape `b` berubah.

In [48]:
# kondisi awal
print(a,'\n')
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [49]:
c = c.reshape((2, 6))

In [50]:
print(a.shape)
print(c.shape)

(3, 4)
(2, 6)


In [51]:
# kondisi setelah ubah shape b
print(a,'\n')
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


Merubah data `c` akan merubah data `a`.

In [52]:
c[0, 4] = 1234

In [53]:
print(a,'\n')
print(c)

[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]] 

[[   0    1    2    3 1234    5]
 [   6    7    8    9   10   11]]


Slicing an array returns a view of it:

In [56]:
s = a[:, 1:3] # semua baris, kolom index 1 hingga index 2
s

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [57]:
s[:] = 10  # s[:] is a view of s. Note the difference between s = 10 and s[:] = 10
s

array([[10, 10],
       [10, 10],
       [10, 10]])

`a` berubah karena `s` diubah:

In [58]:
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

#### *Deep Copy*

The copy method makes a complete copy of the array and its data.



In [59]:
d = a.copy()  # a new array object with new data is created
d is a

False

In [60]:
d.base is a  # d doesn't share anything with a

False

`a` tidak berubah ketika `d` diubah:

In [62]:
d[0, 0] = 9999
d

array([[9999,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

In [61]:
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

Sometimes `copy` should be called after slicing if the original array is not required anymore. For example, suppose `a` is a huge intermediate result and the final result `b` only contains a small fraction of a, a deep copy should be made when constructing `b` with slicing:

In [85]:
a = np.arange(int(1e8)) # data ini memakan memori yang cukup besar
a

array([       0,        1,        2, ..., 99999997, 99999998, 99999999])

Padahal hanya sebagian kecil dari array `a` yang diperlukan; maka hendaknya dilakukan `copy` untuk hasil slicing tersebut sehingga array `a` yang besar tadi bisa dihapus.

In [86]:
b = a[:100].copy()

In [87]:
del a  # the memory of `a` can be released.

If `b = a[:100]` is used instead, `a` is referenced by `b` and will persist in memory even if `del a` is executed.

Mungkin maksudnya: jika tidak dilakukan `copy`, maka array `a` masih memakan memory, walaupun telah dihapus dan tidak dapat dipanggil kembali.

<center><strong>[END][ISOLATED_SECTION]</strong> Copies and Views</center>

Kembali kepada _replicating, joining, or mutating existing arrays_.

There are a number of routines to join existing arrays e.g. `numpy.vstack`, `numpy.hstack`, and `numpy.block`. Here is an example of joining four 2-by-2 arrays into a 4-by-4 array using block: